spring.application.name=marketshop

spring.thymeleaf.cache = false

# ??? ??? ?? ??
# ?? ? ?? ?? ???
spring.servlet.multipart.max-file-size=20MB

# ??? ?? ?? ??
spring.servlet.multipart.max-request-size=100MB



debug=true
itemImgLocation=C:/marketshop-images



uploadPath=file:///C:/marketshop-images/








#??? ?? ???
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG
